var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 玩法基础配置.xlsx SHEET: 玩法基础配置 KEY: level
     */
    var TableBaseRuleConfigList = (function () {
        function TableBaseRuleConfigList() {
        }
        TableBaseRuleConfigList.prototype.GetType = function () { return 'table.TableBaseRuleConfigList'; };
        return TableBaseRuleConfigList;
    }());
    table.TableBaseRuleConfigList = TableBaseRuleConfigList;
    __reflect(TableBaseRuleConfigList.prototype, "table.TableBaseRuleConfigList");
    (function (TableBaseRuleConfigList) {
        var NoticeTriggersItem = (function () {
            function NoticeTriggersItem() {
            }
            return NoticeTriggersItem;
        }());
        TableBaseRuleConfigList.NoticeTriggersItem = NoticeTriggersItem;
        __reflect(NoticeTriggersItem.prototype, "table.TableBaseRuleConfigList.NoticeTriggersItem");
    })(TableBaseRuleConfigList = table.TableBaseRuleConfigList || (table.TableBaseRuleConfigList = {}));
})(table || (table = {}));
//# sourceMappingURL=TableBaseRuleConfigList.js.map