var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 玩法配置.xlsx SHEET: 玩法配置 KEY: level
     */
    var TableGameRuleConfigList = (function () {
        function TableGameRuleConfigList() {
        }
        TableGameRuleConfigList.prototype.GetType = function () { return 'table.TableGameRuleConfigList'; };
        return TableGameRuleConfigList;
    }());
    table.TableGameRuleConfigList = TableGameRuleConfigList;
    __reflect(TableGameRuleConfigList.prototype, "table.TableGameRuleConfigList");
})(table || (table = {}));
//# sourceMappingURL=TableGameRuleConfigList.js.map