var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 房间配置表.xlsx SHEET: Sheet1 KEY: gameId*0xFF
     */
    var TableRoomConfig = (function () {
        function TableRoomConfig() {
        }
        TableRoomConfig.prototype.GetType = function () { return 'table.TableRoomConfig'; };
        return TableRoomConfig;
    }());
    table.TableRoomConfig = TableRoomConfig;
    __reflect(TableRoomConfig.prototype, "table.TableRoomConfig");
    (function (TableRoomConfig) {
        var ChipListItem = (function () {
            function ChipListItem() {
            }
            return ChipListItem;
        }());
        TableRoomConfig.ChipListItem = ChipListItem;
        __reflect(ChipListItem.prototype, "table.TableRoomConfig.ChipListItem");
    })(TableRoomConfig = table.TableRoomConfig || (table.TableRoomConfig = {}));
})(table || (table = {}));
//# sourceMappingURL=TableRoomConfig.js.map