var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 鱼表.xlsx SHEET: Sheet1
     */
    var TableFishConfig = (function () {
        function TableFishConfig() {
        }
        TableFishConfig.prototype.GetType = function () { return 'table.TableFishConfig'; };
        return TableFishConfig;
    }());
    table.TableFishConfig = TableFishConfig;
    __reflect(TableFishConfig.prototype, "table.TableFishConfig");
    (function (TableFishConfig) {
        var ColliderAryItem = (function () {
            function ColliderAryItem() {
            }
            return ColliderAryItem;
        }());
        TableFishConfig.ColliderAryItem = ColliderAryItem;
        __reflect(ColliderAryItem.prototype, "table.TableFishConfig.ColliderAryItem");
    })(TableFishConfig = table.TableFishConfig || (table.TableFishConfig = {}));
    (function (TableFishConfig) {
        var MovieClipAryItem = (function () {
            function MovieClipAryItem() {
            }
            return MovieClipAryItem;
        }());
        TableFishConfig.MovieClipAryItem = MovieClipAryItem;
        __reflect(MovieClipAryItem.prototype, "table.TableFishConfig.MovieClipAryItem");
    })(TableFishConfig = table.TableFishConfig || (table.TableFishConfig = {}));
    (function (TableFishConfig) {
        /**
         * 锚点
         */
        var AnchorOffsetItem = (function () {
            function AnchorOffsetItem() {
            }
            return AnchorOffsetItem;
        }());
        TableFishConfig.AnchorOffsetItem = AnchorOffsetItem;
        __reflect(AnchorOffsetItem.prototype, "table.TableFishConfig.AnchorOffsetItem");
    })(TableFishConfig = table.TableFishConfig || (table.TableFishConfig = {}));
})(table || (table = {}));
//# sourceMappingURL=TableFishConfig.js.map