var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 鱼阵.xlsx SHEET: 鱼阵 KEY: id
     */
    var TableFishTeamConfig = (function () {
        function TableFishTeamConfig() {
        }
        TableFishTeamConfig.prototype.GetType = function () { return 'table.TableFishTeamConfig'; };
        return TableFishTeamConfig;
    }());
    table.TableFishTeamConfig = TableFishTeamConfig;
    __reflect(TableFishTeamConfig.prototype, "table.TableFishTeamConfig");
    (function (TableFishTeamConfig) {
        var FishTeamItem = (function () {
            function FishTeamItem() {
            }
            return FishTeamItem;
        }());
        TableFishTeamConfig.FishTeamItem = FishTeamItem;
        __reflect(FishTeamItem.prototype, "table.TableFishTeamConfig.FishTeamItem");
    })(TableFishTeamConfig = table.TableFishTeamConfig || (table.TableFishTeamConfig = {}));
})(table || (table = {}));
//# sourceMappingURL=TableFishTeamConfig.js.map