var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 道具表.xlsx SHEET: 道具
     */
    var TablePropConfig = (function () {
        function TablePropConfig() {
        }
        TablePropConfig.prototype.GetType = function () { return 'table.TablePropConfig'; };
        return TablePropConfig;
    }());
    table.TablePropConfig = TablePropConfig;
    __reflect(TablePropConfig.prototype, "table.TablePropConfig");
})(table || (table = {}));
//# sourceMappingURL=TablePropConfig.js.map