var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 炮台.xlsx SHEET: 炮台
     */
    var TableBatteryConfig = (function () {
        function TableBatteryConfig() {
        }
        TableBatteryConfig.prototype.GetType = function () { return 'table.TableBatteryConfig'; };
        return TableBatteryConfig;
    }());
    table.TableBatteryConfig = TableBatteryConfig;
    __reflect(TableBatteryConfig.prototype, "table.TableBatteryConfig");
})(table || (table = {}));
//# sourceMappingURL=TableBatteryConfig.js.map