var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 子弹.xlsx SHEET: Sheet1
     */
    var TableBulletConfig = (function () {
        function TableBulletConfig() {
        }
        TableBulletConfig.prototype.GetType = function () { return 'table.TableBulletConfig'; };
        return TableBulletConfig;
    }());
    table.TableBulletConfig = TableBulletConfig;
    __reflect(TableBulletConfig.prototype, "table.TableBulletConfig");
    (function (TableBulletConfig) {
        var ColliderAryItem = (function () {
            function ColliderAryItem() {
            }
            return ColliderAryItem;
        }());
        TableBulletConfig.ColliderAryItem = ColliderAryItem;
        __reflect(ColliderAryItem.prototype, "table.TableBulletConfig.ColliderAryItem");
    })(TableBulletConfig = table.TableBulletConfig || (table.TableBulletConfig = {}));
    (function (TableBulletConfig) {
        var ImageAryItem = (function () {
            function ImageAryItem() {
            }
            return ImageAryItem;
        }());
        TableBulletConfig.ImageAryItem = ImageAryItem;
        __reflect(ImageAryItem.prototype, "table.TableBulletConfig.ImageAryItem");
    })(TableBulletConfig = table.TableBulletConfig || (table.TableBulletConfig = {}));
})(table || (table = {}));
//# sourceMappingURL=TableBulletConfig.js.map