var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 鱼潮表.xls SHEET: Sheet1
     */
    var TableFishBoom = (function () {
        function TableFishBoom() {
        }
        TableFishBoom.prototype.GetType = function () { return 'table.TableFishBoom'; };
        return TableFishBoom;
    }());
    table.TableFishBoom = TableFishBoom;
    __reflect(TableFishBoom.prototype, "table.TableFishBoom");
})(table || (table = {}));
//# sourceMappingURL=TableFishBoom.js.map