var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 路径表.xls SHEET: Sheet1
     */
    var TableFishPath = (function () {
        function TableFishPath() {
        }
        TableFishPath.prototype.GetType = function () { return 'table.TableFishPath'; };
        return TableFishPath;
    }());
    table.TableFishPath = TableFishPath;
    __reflect(TableFishPath.prototype, "table.TableFishPath");
    (function (TableFishPath) {
        var PathConfigItem = (function () {
            function PathConfigItem() {
            }
            return PathConfigItem;
        }());
        TableFishPath.PathConfigItem = PathConfigItem;
        __reflect(PathConfigItem.prototype, "table.TableFishPath.PathConfigItem");
    })(TableFishPath = table.TableFishPath || (table.TableFishPath = {}));
})(table || (table = {}));
//# sourceMappingURL=TableFishPath.js.map